[package]
name = "typecode"
version = "1.0.8"
edition = "2021"

[features]
default = ["all"]
all = ["rust-gen", "go-gen", "ts-gen"]
rust-gen = []
go-gen = []
ts-gen = []

[dependencies]
heck = "0.4.1"
serde = "1.0.185"
serde_derive = "1.0.185"
serde_yaml = "0.9.25"
