[package]
name = "typecode"
version = "0.1.0"
edition = "2021"

[features]
default = ["all"]
all = ["rust-gen", "go-gen", "ts-gen"]
rust-gen = []
go-gen = []
ts-gen = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.1"
